jobs:

  - name: raw_to_bronze

    enabled: true

    mode: batch

    source:

      type: ozone

      path: transaction_stream

      format: json

    sink:

      type: iceberg

      namespace: bronze

      table: transaction_stream

    trigger:

      interval: 5m