jobs:

  - name: raw_to_bronze
    enabled: true
    mode: batch

    source:
      type: ozone
      path: transaction_stream
      format: json

    sink:
      type: iceberg
      namespace: bronze
      table: transaction_stream

    trigger:
      interval: 5m

  - name: bronze_to_silver_cashin
    enabled: true
    mode: batch

    source:
      table: polaris.bronze.transaction_stream

    sink:
      table: polaris.silver.cashin_transaction

    filter:
      processing_code: "400000"
  
  
  - name: bronze_to_silver_cashout
    enabled: true
    mode: batch

    source:
      table: polaris.bronze.transaction_stream

    sink:
      table: polaris.silver.cashout_transaction

    filter:
      processing_code: "280000"
  
  - name: silver_to_gold_cashin
    enabled: true
    mode: batch

    source:
      table: polaris.silver.cashin_transaction

    sink:
      table: polaris.gold.cashin_summary

  
  - name: silver_to_gold_cashout
    enabled: true
    mode: batch

    source:
      table: polaris.silver.cashout_transaction

    sink:
      table: polaris.gold.cashout_summary