EVENTS_PER_SECOND = 300
# PUBLISHER = "console"
PUBLISHER = "kafka"

STATUSES = [
    "SUCCESS",
    "FAILED"
]

MIN_CUSTOMER_ID = 1000000
MAX_CUSTOMER_ID = 9999999

MIN_MERCHANT_ID = 1000
MAX_MERCHANT_ID = 9999

MIN_AMOUNT = 10
MAX_AMOUNT = 5000

# Kafka
KAFKA_BOOTSTRAP_SERVERS = "kafka:9092"
KAFKA_TOPIC = "sales_transactions"

SOURCE = "transaction"