kafka:
  bootstrap_servers: kafka:9092
  consumer_group: sales-consumer-group

clickhouse:
  host: clickhouse
  port: 8123
  database: analytics
  user: dhonuk
  password: ${CLICKHOUSE_PASSWORD}

postgres:
  host: postgres
  port: 5432
  database: analytics
  user: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}

ozone:
  endpoint: ${OZONE_ENDPOINT}
  access_key: ${AWS_ACCESS_KEY_ID}
  secret_key: ${AWS_SECRET_ACCESS_KEY}

logging:
  level: INFO

