connector.name=iceberg

# --------------------------
# Polaris REST Catalog
# --------------------------
iceberg.catalog.type=rest
iceberg.rest-catalog.uri=http://polaris:8181/api/catalog

# Polaris catalog name
iceberg.rest-catalog.warehouse=raw

# OAuth authentication
iceberg.rest-catalog.security=OAUTH2
iceberg.rest-catalog.oauth2.server-uri=http://polaris:8181/api/catalog/v1/oauth/tokens
iceberg.rest-catalog.oauth2.credential=root:s3cr3t
iceberg.rest-catalog.oauth2.scope=PRINCIPAL_ROLE:ALL

# --------------------------
# Apache Ozone (S3)
# --------------------------
fs.native-s3.enabled=true

s3.endpoint=http://ozone-s3g:9878
s3.region=us-east-1
s3.path-style-access=true

s3.aws-access-key=ozone
s3.aws-secret-key=ozone