app:
  name: dhonuk-consumer

kafka:
  bootstrap_servers:
    - kafka:9092
  consumer_group: dhonuk-consumer
  auto_offset_reset: earliest
  enable_auto_commit: false

consumer:
  poll_timeout_ms: 1000

batch:
  size: 500
  flush_interval: 5

clickhouse:
  host: clickhouse
  port: 8123
  username: dhonuk
  password: dhonuk123

logging:
  level: INFO



